### ISSUE TITLE
Blackhole casting exception

### ISSUE THREAD

**Issue by mmisamore** [Frege/frege#168]
Playing around with Frege with the Eclipse plugin, I discovered that this code is throwing an interesting error:

fibMemo :: JArray Int
fibMemo = arrayFromList $  1 : 1 : [fibMemo `elemAt` (i-1) + fibMemo `elemAt` (i-2) | i <- [2..99]]
main = println $ fibMemo `elemAt` 0

This type-checks with the Eclipse plugin but seems to fail at run-time with the error:

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.ClassCastException: frege.runtime.BlackHole cannot be cast to [I
	at examples.Fibonacci$3$1Flc$21845_19879.work(Fibonacci.java:580)
	at examples.Fibonacci$3$1.eval(Fibonacci.java:612)
	at examples.Fibonacci$3$1.eval(Fibonacci.java:1)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.prelude.PreludeList$IListView__lbrack_rbrack$1Flen_21448.work(PreludeList.java:2117)
	at frege.prelude.PreludeList$IListView__lbrack_rbrack.length(PreludeList.java:2137)
	at frege.prelude.PreludeArrays$TJArray.fromList(PreludeArrays.java:3707)
	at frege.prelude.PreludeArrays.arrayFromList(PreludeArrays.java:5983)
	at examples.Fibonacci$Ĳ$arrayFromListƒ20ab04b2.eval(Fibonacci.java:693)
	at frege.runtime.Fun1$1.eval(Fun1.java:63)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at examples.Fibonacci$3.eval(Fibonacci.java:601)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at examples.Fibonacci$4.eval(Fibonacci.java:634)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at examples.Fibonacci$Ĳ$printlnƒcfbbb639.eval(Fibonacci.java:679)
	at examples.Fibonacci$Ĳ$printlnƒcfbbb639.eval(Fibonacci.java:1)
	at frege.runtime.Fun1$1.eval(Fun1.java:63)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at examples.Fibonacci.<clinit>(Fibonacci.java:629)

I discovered this issue when attempting to reproduce something similar to the following Haskell example (which works fine in ghci):

let fib = array (0,99) $ (0,1) : (1,1) : [(i, fib!(i-1) + fib!(i-2)) | i <- [2..99]]
fib ! 99
> 354224848179261915075

**Comment by Ingo60** [comment]
Yes, it is impossible to do it this way.

Unlike in Haskell, the arrays used here are ordinary Java arrays whose alements are not thunks, but primitive integers.

Creation of readonly, pure arrays can only be done at once. Technically, it is an application of the ST monad, whose purpose is to encapsulate impure activities - like array element mutation. But this means once the ST action is run, it must create the whole array and set all elements at once.

It is therefore not possible to reference the array to be created in the list expression given to `arrayFromList`. Perhaps this shoud be noted in the documentation.

You can achieve something similar with the function `arrayCache` that takes a function that computes the value for each index. This function **can** reference the array while it is in the making through its second argument, although only at strictly smaller indexes.

Thus (straight from the online REPL try.frege-lang.org):

    frege> :{
    > fibCache = arrayCache f 100 where
    >     f 0 a = 1
    >     f 1 a = 1
    >     f n a = a `elemAt` (n-1) + a `elemAt` (n-2) :: Integer
    > :}
    function fibCache :: JArray Integer
    frege> fibCache `elemAt` 42
    433494437

Note that without the type annotation on one of the clauses of `f` you would get an `Int` array, which is not what you probably want to use for even small ranges of fibonacci numbers.

**Comment by mmisamore** [comment]
Thanks for the thorough explanation! I figured something like that was going on with ST and the JArray in the background.
