### ISSUE TITLE
Built compiler with class version 52 does not run on Java 7

### ISSUE THREAD

**Issue by ysangkok** [Frege/frege#269]
I can't use Java 8 since it crashes (i know this is a known problem)

After patching the Makefile to work with Busybox's time and switching to run7 and target 1.7, I hit this issue:
```
Making compiler1
/usr/bin/time  java -Dfrege.javac=internal -Xss4m -Xmx2222m -cp build -jar fregec.jar -d build -hints -nocp -prefix a -sp shadow:.  -target 1.7 -make frege.compiler.Main
Exception in thread "main" java.lang.UnsupportedClassVersionError: frege/compiler/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by ysangkok** [comment]
I found the compiler for Java 7 in the releases section.
