### ISSUE TITLE
Recent development version of frege crashes javac when compiling compiler2

### ISSUE THREAD

**Issue by yuxuanchiadm** [Frege/frege#350]
Javac crashed when compiling ```build/bfrege/compiler/Classes.java```.
Using latest OracleJDK 1.8.0_162.
Looks like caused by lambda expr. When compiling ```passC``` javac attempt to generate those code for lambda: ```java.lang.invoke.LambdaMetafactory.metafactory(this)```. So called ```emitop0``` try to generate ```aload_0```. Then compiler crashed.
But OracleJDK 9.0.4 compile frege fine somehow. So code generated by frege should be valid. Looks like caused by bug of java8.
```
java.lang.NullPointerException
        at com.sun.tools.javac.jvm.Code.emitop0(Code.java:559)
        at com.sun.tools.javac.jvm.Items$SelfItem.load(Items.java:367)
        at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:966)
        at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1842)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:947)
        at com.sun.tools.javac.jvm.Gen.visitParens(Gen.java:1977)
        at com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1661)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:947)
        at com.sun.tools.javac.jvm.Gen.visitTypeCast(Gen.java:2264)
        at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:947)
        at com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:966)
        at com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1842)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:947)
        at com.sun.tools.javac.jvm.Gen.visitAssign(Gen.java:1982)
        at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1686)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:947)
        at com.sun.tools.javac.jvm.Gen.visitExec(Gen.java:1781)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
        at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:737)
        at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:772)
        at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:758)
        at com.sun.tools.javac.jvm.Gen.genStats(Gen.java:809)
        at com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1157)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
        at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:737)
        at com.sun.tools.javac.jvm.Gen.genStat(Gen.java:772)
        at com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:1031)
        at com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:994)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
        at com.sun.tools.javac.jvm.Gen.genDef(Gen.java:737)
        at com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2454)
        at com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:745)
        at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1572)
        at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1536)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at frege.runtime.Javac.runJavac(Javac.java:46)
        at afrege.compiler.Main$4.apply(Main.java:4048)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at afrege.prelude.PreludeBase$TST$3$1.call(PreludeBase.java:10590)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$3.apply(PreludeBase.java:10588)
        at afrege.prelude.PreludeBase$TST$2.call(PreludeBase.java:10578)
        at afrege.prelude.PreludeBase$TST$2.call(PreludeBase.java:10576)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.prelude.PreludeBase$WrappedCheckedException.doCatch(PreludeBase.java:7405)
        at afrege.prelude.PreludeIO$6.apply(PreludeIO.java:820)
        at afrege.prelude.PreludeBase$TST$2.call(PreludeBase.java:10578)
        at afrege.prelude.PreludeBase$TST$2.call(PreludeBase.java:10576)
        at frege.run7.Thunk.call(Thunk.java:234)
        at afrege.java.Lang$1.run(Lang.java:3107)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
E .\frege\compiler\Classes.fr:783: java compiler errors
    are most likely caused by erroneous native definitions
```

**Comment by Dierk** [comment]
yep, this is a Java8 compiler bug.
We tried to report it, but it fell on deaf ears.
The Java 9 compiler works here, though (which makes the decline of the bug report by the Java team extra suspicious if you ask me)

**Comment by matil019** [comment]
Same for OpenJDK8 (for completeness).

FYI, if you add type annotations to `where`/`let` declarations, the error goes away in some cases. This is because the structure of generated Java code differs. **NOTE:** I added type annotations to `passC` but it did *not* fix the issue.

**Comment by Ingo60** [comment]
I suggest you all stop wasting your time on that. It's a null pointer error
in java 8 compiler, no more, no less. And it's not going to change.



matil019 <notifications@github.com> schrieb am Mo., 26. März 2018, 06:09:

**Comment by yuxuanchiadm** [comment]
Ok. I'll update wiki page and close this issue.
