### ISSUE TITLE
Frege Gradle Plugin fails on JDK 12

### ISSUE THREAD

**Issue by russel** [Frege/frege#377]
It appears that the Frege plugin for Gradle fails when using JDK 12:
```
* Exception is:
java.lang.NoSuchMethodError: org.gradle.api.plugins.JavaBasePlugin.configureForSourceSet(Lorg/gradle/api/tasks/SourceSet;Lorg/gradle/api/tasks/compile/AbstractCompile;)V
        at frege.gradle.plugins.FregeBasePlugin$1.execute(FregeBasePlugin.java:66)
        at frege.gradle.plugins.FregeBasePlugin$1.execute(FregeBasePlugin.java:47)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
…
```

**Comment by Dierk** [comment]
I assume this has only indirectly to do with Java 12 as supporting this requires a newer version of Gradle, which in turn changed some API that the Frege Plugin relies upon. I tried to update a few weeks ago but could get it working in the time available. Current plans are to address this issue in a hackergarten when some Gradle expert is around

**Comment by russel** [comment]
I am using Gradle 5.4.1.
