### ISSUE TITLE
FregeDoc on dkre

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#392]

**Comment by szabi** [comment]
Hi, Dirk,

I see you've performed some clean-up tasks on the Frege repo recently.

Do you have some plans for the project looking forward?

**Comment by Dierk** [comment]
Yes, I work on the project when time allows - and every now and then, I have master students working on it - or with it, see https://dierk.github.io/Home/
Do you have any specific reason for asking?

**Comment by renatoathaydes** [comment]
Just so you know: Frege does not appear to work on Java 11+.

The last artifact published on Maven Central: `Last updated: Tue, 29 Sep 2015 18:55:08 +0200`

So I guess this project has been pretty much abandoned for a long time.

The error I get is this:

```
Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
        at frege.interpreter.FregeInterpreter$36.eval(FregeInterpreter.java:7589)
        at frege.interpreter.FregeInterpreter$36.eval(FregeInterpreter.java:7541)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
...
Caused by: frege.runtime.Undefined: strange java.specification.version: Just "11"
        at frege.prelude.PreludeBase.error(PreludeBase.java:17968)
        at frege.compiler.types.Targets$1$1.eval(Targets.java:831)
        at frege.runtime.Delayed.call(Delayed.java:198)
        at frege.runtime.Delayed.forced(Delayed.java:257)
        at frege.prelude.Maybe.fromMaybe(Maybe.java:1247)
        at frege.compiler.types.Targets$1.eval(Targets.java:828)
        at frege.compiler.types.Targets$1.eval(Targets.java:821)
        at frege.runtime.Delayed.call(Delayed.java:198)
        at frege.runtime.Delayed.forced(Delayed.java:267)
        at frege.compiler.common.CompilerOptions.<clinit>(CompilerOptions.java:366)
```

**Comment by Ingo60** [comment]
No wonder, as the Maven Version is totally out of date. 
You cannot use it.

**Comment by JoshTRN** [comment]
Damn. I have to work with Java every day. But I have a lot of flexibility within that. If this were up to date, I'd be so psyched to be able to use it. 😞

**Comment by Dierk** [comment]
@JoshTRN  is it the maven support in particular that you need for using Frege? If so, we can give it a bit more love.

**Comment by talios** [comment]
I wasn't aware that Frege itself was still maintained; it probably wouldn't be that difficult to update the plugin. The main problem was that there weren't any Frege jars being published to Maven Central, other than the Frege OSGi-patched versions I was maintaining at the time for my own purposes.

Is that still the case?

**Comment by Dierk** [comment]
@talios yes, publishing to one of the central maven repos has always been extra work that we avoided. If I'm not mistaken, one could use the github releases for maven dependency management (?)

**Comment by renatoathaydes** [comment]
I have nothing against this project, but if I were to pick a functional programming language that runs on the JVM, I might go with [Flix](https://flix.dev) instead, or the more established Scala 3 @JoshTRN .

**Comment by Dierk** [comment]
@renatoathaydes well, many other approaches are of course also valid. The Frege project focusses on bringing FP to the JVM in the Haskell style while retaining its benefits when calling into Java.
